name: 'dbt_movies_elt'
version: '1.0.0'
profile: 'dbt_movies_elt'

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Cleanup
clean-targets:
  - "target"
  - "dbt_packages"

# Model Materialization Defaults
models:
  dbt_movies_elt:
    example:
      +materialized: view
    dim:
      +materialized: table
        
